{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e3bb4225-7427-4eb4-ac46-41f8f449bb22",
   "metadata": {},
   "outputs": [],
   "source": [
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import streamlit as st\n",
    "\n",
    "# ==============================================================================\n",
    "# STREAMLIT PAGE CONFIGURATION\n",
    "# ==============================================================================\n",
    "st.set_page_config(\n",
    "    page_title=\"Retirement Master Simulator\",\n",
    "    page_icon=\"📈\",\n",
    "    layout=\"wide\",\n",
    ")\n",
    "\n",
    "st.title(\"📈 Household Retirement & Tax Simulator\")\n",
    "st.markdown(\n",
    "    \"Model your dual-income retirement trajectory, test return rates, and view\"\n",
    "    \" tax impacts interactively.\"\n",
    ")\n",
    "\n",
    "# ==============================================================================\n",
    "# SIDEBAR: CONFIGURATION INPUTS\n",
    "# ==============================================================================\n",
    "st.sidebar.header(\"⚙️ Simulation Inputs\")\n",
    "\n",
    "with st.sidebar.expander(\"📊 Macro & Return Assumptions\", expanded=True):\n",
    "  annual_return = (\n",
    "      st.number_input(\n",
    "          \"Annual Compound Return Rate (%)\",\n",
    "          min_value=0.0,\n",
    "          max_value=15.0,\n",
    "          value=6.0,\n",
    "          step=0.25,\n",
    "      )\n",
    "      / 100.0\n",
    "  )\n",
    "  target_income = st.number_input(\n",
    "      \"Target Annual Gross Income ($CAD)\",\n",
    "      min_value=50000,\n",
    "      max_value=500000,\n",
    "      value=230000,\n",
    "      step=5000,\n",
    "  )\n",
    "  life_expectancy = st.slider(\"Model End Age (Life Expectancy)\", 80, 100, 90)\n",
    "\n",
    "with st.sidebar.expander(\"👥 Household Timeline\", expanded=False):\n",
    "  current_age_user = st.number_input(\"Your Current Age\", 20, 80, 51)\n",
    "  current_age_spouse = st.number_input(\"Spouse's Current Age\", 20, 80, 51)\n",
    "  retirement_age_user = st.number_input(\n",
    "      \"Your Target Retirement Age\", 50, 75, 65\n",
    "  )\n",
    "  retirement_age_spouse = st.number_input(\n",
    "      \"Spouse's Target Retirement Age\", 50, 75, 60\n",
    "  )\n",
    "\n",
    "with st.sidebar.expander(\"💰 Starting Portfolio Assets\", expanded=False):\n",
    "  user_rrsp = st.number_input(\"User RRSP / RRIF\", value=443000)\n",
    "  user_lira = st.number_input(\"User LIRA / LIF\", value=562000)\n",
    "  user_tfsa_mf = st.number_input(\"User TFSA Mutual Funds\", value=81000)\n",
    "  user_tfsa_etf = st.number_input(\"User TFSA ETFs\", value=75000)\n",
    "  user_mutual_funds = st.number_input(\"User Non-Reg Mutual Funds\", value=653000)\n",
    "  spouse_rrsp = st.number_input(\"Spouse RRSP\", value=376550)\n",
    "  spouse_tfsa = st.number_input(\"Spouse TFSA\", value=156000)\n",
    "  spouse_tfsa_mf = st.number_input(\"Spouse Non-Reg Mutual Funds\", value=80000)\n",
    "  ul_initial_cash_value_each = st.number_input(\n",
    "      \"UL Cash Value (Each Policy)\", value=62000\n",
    "  )\n",
    "\n",
    "with st.sidebar.expander(\"📥 Annual Contributions\", expanded=False):\n",
    "  user_rrsp_annual_contrib = st.number_input(\n",
    "      \"User Annual RRSP Contribution\", value=32000\n",
    "  )\n",
    "  user_tfsa_annual_contrib = st.number_input(\n",
    "      \"User Annual TFSA Contribution\", value=7500\n",
    "  )\n",
    "  spouse_rrsp_annual_contrib = st.number_input(\n",
    "      \"Spouse Annual RRSP Contribution\", value=15000\n",
    "  )\n",
    "  spouse_tfsa_annual_contrib = st.number_input(\n",
    "      \"Spouse Annual TFSA Contribution\", value=7500\n",
    "  )\n",
    "\n",
    "with st.sidebar.expander(\"🛡️ Pensions & Guaranteed Income\", expanded=False):\n",
    "  cpp_oas_annual = st.number_input(\n",
    "      \"Gov CPP & OAS Combined (Age 65+)\", value=53800\n",
    "  )\n",
    "  spouse_company_pension = st.number_input(\n",
    "      \"Spouse Company Pension (Starts at Spouse Retirement)\", value=35000\n",
    "  )\n",
    "\n",
    "\n",
    "# ==============================================================================\n",
    "# TAX & RRIF ENGINES\n",
    "# ==============================================================================\n",
    "def get_rrif_minimum_pct(age):\n",
    "  rates = {\n",
    "      71: 0.0528,\n",
    "      72: 0.0540,\n",
    "      73: 0.0553,\n",
    "      74: 0.0567,\n",
    "      75: 0.0582,\n",
    "      76: 0.0598,\n",
    "      77: 0.0617,\n",
    "      78: 0.0636,\n",
    "      79: 0.0658,\n",
    "      80: 0.0682,\n",
    "      81: 0.0708,\n",
    "      82: 0.0738,\n",
    "      83: 0.0771,\n",
    "      84: 0.0808,\n",
    "      85: 0.0851,\n",
    "      86: 0.0900,\n",
    "      87: 0.0955,\n",
    "      88: 0.1021,\n",
    "      89: 0.1099,\n",
    "      90: 0.1192,\n",
    "  }\n",
    "  if age < 71:\n",
    "    return 0.0\n",
    "  return rates.get(age, 0.20)\n",
    "\n",
    "\n",
    "def estimate_alberta_tax(gross_income):\n",
    "  if gross_income <= 0:\n",
    "    return 0.0\n",
    "  if gross_income <= 58523:\n",
    "    tax = gross_income * 0.22\n",
    "  elif gross_income <= 117045:\n",
    "    tax = 12875 + (gross_income - 58523) * 0.305\n",
    "  elif gross_income <= 181440:\n",
    "    tax = 30724 + (gross_income - 117045) * 0.38\n",
    "  else:\n",
    "    tax = 55194 + (gross_income - 181440) * 0.42\n",
    "  return round(tax, -2)\n",
    "\n",
    "\n",
    "# ==============================================================================\n",
    "# SIMULATION EXECUTION LOOP\n",
    "# ==============================================================================\n",
    "start_age = current_age_user\n",
    "end_age = life_expectancy\n",
    "r = annual_return\n",
    "\n",
    "u_rrsp, u_lira, u_tfsa_mf, u_tfsa_etf, u_mf = (\n",
    "    user_rrsp,\n",
    "    user_lira,\n",
    "    user_tfsa_mf,\n",
    "    user_tfsa_etf,\n",
    "    user_mutual_funds,\n",
    ")\n",
    "s_rrsp, s_tfsa, s_mf = spouse_rrsp, spouse_tfsa, spouse_tfsa_mf\n",
    "ul_user, ul_spouse = ul_initial_cash_value_each, ul_initial_cash_value_each\n",
    "\n",
    "results = []\n",
    "\n",
    "for age in range(start_age, end_age + 1):\n",
    "  spouse_age_current = current_age_spouse + (age - start_age)\n",
    "  user_is_working = age < retirement_age_user\n",
    "  spouse_is_working = spouse_age_current < retirement_age_spouse\n",
    "  is_retired = (age >= retirement_age_user) or (\n",
    "      spouse_age_current >= retirement_age_spouse\n",
    "  )\n",
    "\n",
    "  pensions = 0.0\n",
    "  required_draw = 0.0\n",
    "  total_gross = 0.0\n",
    "  est_tax = 0.0\n",
    "  eff_tax_rate = 0.0\n",
    "\n",
    "  if is_retired:\n",
    "    if spouse_age_current >= retirement_age_spouse:\n",
    "      pensions += spouse_company_pension\n",
    "    if age >= 65:\n",
    "      pensions += cpp_oas_annual\n",
    "\n",
    "    if age >= 71:\n",
    "      u_rrif_min = u_rrsp * get_rrif_minimum_pct(age)\n",
    "      u_lira_min = u_lira * get_rrif_minimum_pct(age)\n",
    "      s_rrif_min = s_rrsp * get_rrif_minimum_pct(age)\n",
    "      required_draw = round(u_rrif_min + u_lira_min + s_rrif_min, 2)\n",
    "    else:\n",
    "      required_draw = max(0.0, target_income - pensions)\n",
    "\n",
    "    total_gross = round(required_draw + pensions, 2)\n",
    "    est_tax = estimate_alberta_tax(total_gross)\n",
    "    eff_tax_rate = (\n",
    "        round((est_tax / total_gross) * 100, 1) if total_gross > 0 else 0.0\n",
    "    )\n",
    "\n",
    "  total_portfolio = round(\n",
    "      u_rrsp\n",
    "      + u_tfsa_mf\n",
    "      + u_tfsa_etf\n",
    "      + u_mf\n",
    "      + u_lira\n",
    "      + s_rrsp\n",
    "      + s_tfsa\n",
    "      + s_mf\n",
    "      + ul_user\n",
    "      + ul_spouse,\n",
    "      2,\n",
    "  )\n",
    "\n",
    "  results.append({\n",
    "      \"Age\": age,\n",
    "      \"Spouse Age\": spouse_age_current,\n",
    "      \"Portfolio Drawdown\": round(required_draw, 0),\n",
    "      \"Pensions\": round(pensions, 0),\n",
    "      \"Total Gross Income\": round(total_gross, 0),\n",
    "      \"Est. Tax Paid\": round(est_tax, 0),\n",
    "      \"Effective Tax Rate (%)\": eff_tax_rate,\n",
    "      \"Total Household Portfolio\": total_portfolio,\n",
    "  })\n",
    "\n",
    "  if age < end_age:\n",
    "    draw_ratio = 0.0\n",
    "    if is_retired and (u_rrsp + u_lira + s_rrsp) > 0:\n",
    "      draw_ratio = required_draw / (u_rrsp + u_lira + s_rrsp)\n",
    "\n",
    "    u_rrsp = max(0.0, u_rrsp - (u_rrsp * draw_ratio))\n",
    "    u_lira = max(0.0, u_lira - (u_lira * draw_ratio))\n",
    "    s_rrsp = max(0.0, s_rrsp - (s_rrsp * draw_ratio))\n",
    "\n",
    "    if user_is_working:\n",
    "      u_rrsp += user_rrsp_annual_contrib\n",
    "      u_tfsa_mf += user_tfsa_annual_contrib * 0.5\n",
    "      u_tfsa_etf += user_tfsa_annual_contrib * 0.5\n",
    "    if spouse_is_working:\n",
    "      s_rrsp += spouse_rrsp_annual_contrib\n",
    "      s_tfsa += spouse_tfsa_annual_contrib\n",
    "\n",
    "    u_rrsp *= 1 + r\n",
    "    u_lira *= 1 + r\n",
    "    u_tfsa_mf *= 1 + r\n",
    "    u_tfsa_etf *= 1 + r\n",
    "    u_mf *= 1 + r\n",
    "    s_rrsp *= 1 + r\n",
    "    s_tfsa *= 1 + r\n",
    "    s_mf *= 1 + r\n",
    "    ul_user *= 1 + r\n",
    "    ul_spouse *= 1 + r\n",
    "\n",
    "df_master = pd.DataFrame(results)\n",
    "\n",
    "# ==============================================================================\n",
    "# DASHBOARD OUTPUT DISPLAY\n",
    "# ==============================================================================\n",
    "st.subheader(\"📊 Projection Summary Schedule\")\n",
    "display_ages = [\n",
    "    start_age,\n",
    "    55,\n",
    "    60,\n",
    "    64,\n",
    "    retirement_age_user,\n",
    "    66,\n",
    "    70,\n",
    "    71,\n",
    "    75,\n",
    "    80,\n",
    "    85,\n",
    "    end_age,\n",
    "]\n",
    "display_ages = sorted(list(set([a for a in display_ages if a <= end_age])))\n",
    "df_display = df_master[df_master[\"Age\"].isin(display_ages)]\n",
    "\n",
    "st.dataframe(\n",
    "    df_display.style.format({\n",
    "        \"Spouse Age\": \"{:.0f}\",\n",
    "        \"Portfolio Drawdown\": \"${:,.0f}\",\n",
    "        \"Pensions\": \"${:,.0f}\",\n",
    "        \"Total Gross Income\": \"${:,.0f}\",\n",
    "        \"Est. Tax Paid\": \"${:,.0f}\",\n",
    "        \"Effective Tax Rate (%)\": \"{}%\",\n",
    "        \"Total Household Portfolio\": \"${:,.0f}\",\n",
    "    }),\n",
    "    use_container_width=True,\n",
    ")\n",
    "\n",
    "# Plotting\n",
    "st.subheader(\"📈 Visual Trends\")\n",
    "fig, axes = plt.subplots(nrows=2, ncols=1, figsize=(10, 8), sharex=True)\n",
    "\n",
    "axes[0].plot(\n",
    "    df_master[\"Age\"],\n",
    "    df_master[\"Total Household Portfolio\"] / 1e6,\n",
    "    label=f\"Total Portfolio ($M) @ {r*100:.1f}% Return\",\n",
    "    color=\"navy\",\n",
    "    linewidth=2.5,\n",
    ")\n",
    "axes[0].set_ylabel(\"Portfolio Value ($ Millions)\")\n",
    "axes[0].grid(True, linestyle=\":\", alpha=0.6)\n",
    "axes[0].legend(loc=\"upper left\")\n",
    "\n",
    "axes[1].bar(\n",
    "    df_master[\"Age\"],\n",
    "    df_master[\"Pensions\"] / 1e3,\n",
    "    label=\"Pensions\",\n",
    "    color=\"skyblue\",\n",
    ")\n",
    "axes[1].bar(\n",
    "    df_master[\"Age\"],\n",
    "    df_master[\"Portfolio Drawdown\"] / 1e3,\n",
    "    bottom=df_master[\"Pensions\"] / 1e3,\n",
    "    label=\"Portfolio Drawdowns\",\n",
    "    color=\"royalblue\",\n",
    ")\n",
    "axes[1].plot(\n",
    "    df_master[\"Age\"],\n",
    "    df_master[\"Est. Tax Paid\"] / 1e3,\n",
    "    label=\"Est. Tax Paid ($k)\",\n",
    "    color=\"crimson\",\n",
    "    linewidth=2,\n",
    ")\n",
    "axes[1].set_xlabel(\"Your Age\")\n",
    "axes[1].set_ylabel(\"Annual Amount ($k)\")\n",
    "axes[1].grid(True, linestyle=\":\", alpha=0.6)\n",
    "axes[1].legend(loc=\"upper left\")\n",
    "\n",
    "st.pyplot(fig)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.1+"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
